"""Add description column to canteens table

Revision ID: 1bab82679e77
Revises: 
Create Date: 2024-11-22 02:15:34.470496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bab82679e77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canteen')
    op.drop_table('menu')
    with op.batch_alter_table('canteens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canteens', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ingredients', sa.TEXT(), nullable=False),
    sa.Column('nutrition', sa.TEXT(), nullable=False),
    sa.Column('canteen_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['canteen_id'], ['canteen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canteen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
